<?php

namespace GestionBundle\Repository;

/**
 * PermutationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermutationRepository extends \Doctrine\ORM\EntityRepository
{
}
