<?php

namespace EnseignantBundle\Repository;

/**
 * MoyenneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoyenneRepository extends \Doctrine\ORM\EntityRepository
{
}
