<?php

namespace ScolariteBundle\Repository;

/**
 * CoeffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoeffRepository extends \Doctrine\ORM\EntityRepository
{
}
