<?php

namespace ScolariteBundle\Repository;

/**
 * MatiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatiereRepository extends \Doctrine\ORM\EntityRepository
{

    public function MEleve()
    {/*
        $em= $query = $this->getEntityManager();
        $RAW_QUERY= "SELECT moyennes.id_semestre, (coeff.valeur* moyennes.moyenne) 
            as moyM , sum((coeff.valeur* moyennes.moyenne)) as hh ,
            ( sum((coeff.valeur* moyennes.moyenne))/ sum(coeff.valeur) ) as ahah 
            from coeff inner join moyennes on coeff.matiere_id= moyennes.id_matiere
             and coeff.niveau_id=(select distinct f.classe_id from moyennes m inner join
              fos_user f on f.id= m.id_eleve inner join classe c on f.classe_id =c.id 
              where f.id=8 and m.id_semestre =1 ) and moyennes.id_semestre=1 GROUP by moyennes.id_semestre";
        $statement= $em->getConnection()->prepare($RAW_QUERY);
       // $statement->bindValue();
        $result=$statement->fetchAll();
        var_dump($result);
        return $result;*/
    }

}
