EnseignantBundle\Entity\Moyenne:
    type: entity
    table: null
    repositoryClass: EnseignantBundle\Repository\MoyenneRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        m1:
            type: float
            nullable: true
            column: M1
        m2:
            type: float
            nullable: true
            column: M2
        m3:
            type: float
            nullable: true
            column: M3
    lifecycleCallbacks: {  }
